# Generated by Django 4.1.5 on 2023-02-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=100)),
                ('Mobileno', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Company', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='join',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=100)),
                ('Mobileno', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='put',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Company', models.CharField(max_length=100)),
                ('Website', models.CharField(max_length=100)),
                ('Mobileno', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
